duo-labs/cloudmapper

- cloudmapper/webserver.py
responding to svg data from web server, its mime type should be " image/svg+xml" instead of "application/octet-stream"
> add svg mime/type

- cloudmapper/webserver.py
> Add IPv6 support to server

- cloudmapper/gatherer.py
- cloudmapper/prepare.py
This PR tries to solve https://github.com/duo-labs/cloudmapper/issues/22
As far as I have no test data for that, I couldn't test that it is working properly. I can do it if someone has test data to share.
> Add ALB and NLB fetching

- cloudmapper/gatherer.py
- cloudmapper/prepare.py
- collect_data.sh
- demo/us-east-1/describe-load-balancers-v2.json
- tests/unit/test_prepare.py
Solves #22.
Added the python collection part from #61, thanks @JulesDT.
> ALB and NLP support

- README.md
- commands/prepare.py
- commands/stats.py
- requirements-dev.txt
- shared/common.py
- tests/unit/test_prepare.py
Add command to show count of resources
> Add stats command

- collect_commands.yaml
Fixing https://github.com/duo-labs/cloudmapper/issues/91
> Fix collect for commands that require arrays

- README.md
- collect_data.sh
- docs/network_visualizations.md
- entrypoint.sh
I had considerable difficulties in getting Cloudmapper to run at first. With these fixes, it works better.
> Minor fixes to scripts and documentation

- vendor_accounts.yaml
Added account ids so that CloudTrail accounts are not unknown for wot command
> Added AWS CloudTrail account ids to vendor_accounts.yaml

- commands/collect.py
- shared/common.py
i.e. any python string of the form b'str'
Fixes #127
> Update json deserializer to handle bytes literals

- README.md
> install pip for linux

- collect_commands.yaml
- commands/prepare.py
- shared/nodes.py
Added a few commands to collect_commands.yaml to pull in ALB/NLB info on target groups and some code in prepare to go through those target groups to add connections from the ELBs to their respective instances.
> Add support for connections FROM elbs. Includes fixing ELB ARNs

- cloudmapper/nodes.py
Truncate increased. CIDRs added to VPC and Subnet titles.
Example implementation for #67.
> Increases truncate limit, adds CIDRs to titles

- commands/prepare.py
- shared/nodes.py
- web/icons/aws/vpc_endpoint.svg
- web/style.json
Adds support for Interface (PrivateLink) and Gateway (S3 and DynamoDB) endpoints.
> Add VPC endpoint support

- README.md
> Add lightsail:GetLoadBalancers privilege

- web/js/cloudmap.js
> added alert on error fetching data.json

- commands/collect.py
> Return error code on errors for collect

- commands/public.py
> Output valid JSON

- Pipfile
- shared/public.py
Fix a bug that apparently was being hidden.  Resolves #517
> Update pyjq to version 2.3.1; 

- config/audit_config_override.yaml.example
- config/custom_auditor.py
- shared/audit.py
Resolves #556.  Allows you to have your own custom auditors, and also your own custom filtering code.
> Muting improvements; Custom auditors

- auditor/lib/cloudmapperauditor-stack.js
- auditor/s3_bucket_files/cdk_app.yaml
- auditor/s3_bucket_files/run_cloudmapper.sh
- commands/audit.py
- commands/report.py
- shared/audit.py
> Filter alerts by severity

- shared/audit.py
> Fix exfil checker issues

- commands/collect.py
This PR fixes #671 by handling two additional KMS exceptions generated for restricted keys.
> fix #671 by handling kms exceptions on collect

- README.md
- auditor/README.md
- docs/network_visualizations.md
> Fix links that were going to old master branch

- shared/nodes.py
Fixing error "Cannot iterate over null(null)"
> Fixing error "Cannot iterate over null(null)"

- commands/collect.py
Hi
When I tried to use cloudmapper, I faced issue#733 and it seemed not solved yet. So according to [this comment](https://github.com/duo-labs/cloudmapper/issues/733#issuecomment-655682256), I added new exception.
> Added another exception Issue#733

- requirements.txt
Tested on both python 3.7 and 3.9
> pandas 1.13 for python 3.9 support

- auditor/lib/cloudmapperauditor-stack.js
- commands/audit.py
- commands/iam_report.py
- commands/sg_ips.py
- config/custom_auditor.py
- shared/audit.py
- templates/iam_report.html
- templates/report.html
- Small typo in `shared/audit.py` meant that the `audit_accessanalyzer()` check was failing to run.
- clarified command arguments
- general housekeeping
> Access analyzer

- audit_config.yaml
Grammar improvements to the audit_config.yaml file.
> Grammar improvements

- requirements.txt
I encountered issue #875. 
I fixed requirements.txt by upgrading dependencies one by one.
I confirmed this change works by running followings.
run installation command
```
python3 -m venv ./venv && source venv/bin/activate
pip install -r requirements.txt
```
run demo
```
python cloudmapper.py prepare --config config.json.demo --account demo
python cloudmapper.py report --config config.json.demo --account demo
python cloudmapper.py webserver
```
run test
```
make test
```
> Update requirements.txt for #875

- collect_commands.yaml
I've added the securityhub describe-hub endpoint for data collection. Please let me know if there is anything else required to merge this.
> Add securityhub describe-hub to collect commands

- requirements.txt
Reverts duo-labs/cloudmapper#847
> Revert "Fix issue 803"

- commands/collect.py
Done what @0xdabbad00 said in the issue https://github.com/duo-labs/cloudmapper/issues/611 :
Improved the description of `--clean`
> Fix issue 611

- shared/public.py
Fixes issue #718 by uncommenting the code and merging the conditionals
> Fix issue 718

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- commands/prepare.py
Fixes issue #802 by updating what @0xdabbad00 said.
> Fix issue 802

- shared/iam_audit.py
Fixes issue https://github.com/duo-labs/cloudmapper/issues/620 by adding the deprecated policy to the list of bad policies
> Fix issue 620

- account-data/demo/us-east-1/iam-get-account-authorization-details.json
- account-data/demo/us-east-1/iam-get-user/USER
- account-data/demo/us-east-1/iam-get-user/USER_WITH_BAD_INLINE_POLICY
- shared/iam_audit.py
This PR fixes issue #855. It also adds demo user and group data to `account-data/demo/` to demonstrate the fix.
> Fix issue 855

- commands/weboftrust.py
Tidied up some formatting, but also added a block to check for AWS SSO auto-generated roles for `weboftrust.py`
> added weboftrust support for AWS SSO.

- collect_commands.yaml
- stats_config.yaml
Added new items to stats and collect command
> Added new items to stats and collect command

- vendor_accounts.yaml
Cloudability appears twice, putting sources together.
Databricks appears twice with the same values.
509560245411 account appears twice. dynatrace and dyntrace: it seems dynatrace is the correct one.
Lucidchart appears twice with the same info.
314658760392 StackDriver appears twice, putting sources together.
> Updating list

- Dockerfile
This should fix the problems I outlined in issue #890
> fix: docker container did not build issue-890
