- cloudmapper/nodes.py
This is the most "standard" way of using the __eq__ operator, at least according to the doc https://docs.python.org/2/reference/datamodel.html. By making this change I was able to execute the prepare operation without problem, but I can't confirm it didn't change the previous behavior.
> Fix __eq__ operator in Connection class

- cloudmapper/webserver.py
Otherwise you get no feedback and have to traverse the source to figure out what the default port is.
> Show host/port when serving

- README.md
- cloudmapper.py
- cloudmapper/configure.py
Second try at solving https://github.com/duo-labs/cloudmapper/issues/3
I took your comment into account and the config CLI now works that way.
Tested with:
```
python cloudmapper.py configure add-account --config-file config.json --id 123456789012 --name demo --default True
python cloudmapper.py configure add-cidr --config-file config.json --cidr 2.2.2.2/28 --name "NY Office"
python cloudmapper.py configure add-cidr --config-file config.json --cidr 1.1.1.1/32 --name "SF Office"
python cloudmapper.py configure remove-cidr --config-file config.json --cidr 1.1.1.1/32
python cloudmapper.py configure remove-cidr --config-file config.json --name "SF Office"
python cloudmapper.py configure remove-cidr --config-file config.json --name "NY Office"
python cloudmapper.py configure remove-account …
```
> Add configure CLI

- cloudmapper.py
- cloudmapper/gatherer.py
- cloudmapper/prepare.py
- tests/unit/test_prepare.py
- Added support for filtering by VPC name or ID when running the `prepare `command.  
- Added support for passing in a profile name when running the `gather` command.
- Removed the need for the account_name when running the `gather`.  It will now pull from the config
- Added a `clean` switch for the `gather` command to remove the account name directory before proceeding.   Not sure if this is needed, as I did it when I was originally adding the vpc flitering during the gather process, but walked that back.  Left it in just in case.
> Added support for filter by vpc [id/name]

- README.md
When I first read this part of the README, it wasn't immediately clear that the minimal access policy was for the network viz only (then was suprised when I saw auth errors during collection and re-read more closely).  This updates that portion to be more explicit. I'm happy to change the exact wording if desired.
> docs(README): Access policiy clarification

- commands/wot.py
When using ADFS running the ./cloudmapper.py would not work due to the SAML provider not being a known principal for IAM trusts. This fix resolves the issue by adding 'saml-provider/adfs' to if/elif statements.
> added ADFS SAML to principals for WoT

- commands/prepare.py
- docs/network_visualizations.md
- shared/nodes.py
- tests/unit/test_prepare.py
Multiple instances in the same subnet will collapse because of the same id, but when in different subnets they'll get a new id and get rendered.
Now this is taking advantage of the fact that crytoscape only renders one node per ID, there must be a more pragmatic approach to not outputting collapsed nodes at all. But it seems like a fine quick dirty fix.
Is this viable?
**Update**: Ended up going with your first suggestion with `--collapse-asgs`.
> Optionally collapse ASGS

- docs/network_visualizations.md
The last image, "initial layout", in the "Network visualizations" page is broken because a slash ("/") is missing, see: https://github.com/duo-labs/cloudmapper/blob/master/docs/network_visualizations.md
I fixed the URL so that it links to the image as seen here: https://github.com/synoa/cloudmapper/blob/fix/broken-image-docs/docs/network_visualizations.md
> Docs: Fix image URL in Network visualizations 

- README.md
I'm pretty sure in my last PR the Travis build was working. Now it was broken by accepting recent PRs. I think it is best to add the badge on the main README to make sure that the travis build is always passing :)
> add travis badge to the main README

- collect_commands.yaml
One possible solution for issue #209.   This sets the parameter to default as 'All', retrieving all attribute data about the queue.
Contents of file generated for queue url:
```{
"Attributes": {
"ApproximateNumberOfMessages": "0",
"ApproximateNumberOfMessagesDelayed": "0",
"ApproximateNumberOfMessagesNotVisible": "0",
"CreatedTimestamp": "1533944584",
"DelaySeconds": "0",
"LastModifiedTimestamp": "1534547074",
"MaximumMessageSize": "262144",
"MessageRetentionPeriod": "345600",
"QueueArn": "arn:aws:sqs:::",
"ReceiveMessageWaitTimeSeconds": "0",
"VisibilityTimeout": "30"
}
}
```
> add AttributeNames parameter to sqs get-queue-attributes command

- README.md
Hi,
for macOS X, we need to install pipenv via brew.
Maybe it's also needed for linux ?
Thanks.
> DOC: Add pipenv installation for macOS X

- commands/collect.py
Some of AWS account configuration with security constraints  (bound to some region),
prevents of using cloudmapper because it crashes even on the descrbieRegions.
> Allow to specify default region used to query universal services.

- README.md
The SecurityAudit policy now has everything. See https://github.com/SummitRoute/aws_managed_policies/commit/df4502d37e7126d9e5fe8add38cd9ab8aed8f3eb#diff-831d569bb19b182bb12f48b976d5c98fR59
> Remove unneeded extra policy 

- shared/nodes.py
- Fix indexes because TagDescriptions field is list
- Avoid to return None when mismatching
- The None causes error in `add_node_to_subnets()`
> Fix node methods

- shared/audit.py
- shared/public.py
Found 2 problems when generating reports:
1. Some EC2 instances might not have Tags
2. Security groups are declared as set and cannot be serialized to JSON
> Problems when generating report

- README.md
Changed `git clone` instruction in examples to use `https` instead of `ssh`.
Reason:
```
$ git clone git@github.com:duo-labs/cloudmapper.git
Cloning into 'cloudmapper'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
$ git clone https://github.com/duo-labs/cloudmapper.git
Cloning into 'cloudmapper'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 2716 (delta 36), reused 62 (delta 28), pack-reused 2629
Receiving objects: 100% (2716/2716), 7.31 MiB | 2.56 MiB/s, done.
Resolving deltas: 100% (1409/1409), done.
```
> Update README.md (ssh -> https in git clone)

- commands/audit.py
- utils/toslack.py
Flag to write the audit output as markdown so it can be piped to Slack, and a simple utility to send that text to Slack. Example screenshots below.
> Slack output

- commands/report.py
While using this tool to generate a combined report for a number of accounts I would get this error (while using `all` and listing accounts manually):
```
jshodd > cloudmapper > python cloudmapper.py report --accounts product,test
* Getting resource counts
- product
- test
* Getting IAM data
- product
- test
* Getting public resource data
- product
- test
* Auditing accounts
Traceback (most recent call last):
File "cloudmapper.py", line 72, in <module>
main()
File "cloudmapper.py", line 66, in main
commands[command].run(arguments)
File "/Users/jshodd/opt/tools/cloudmapper/commands/report.py", line 454, in run
report(accounts, config, args)
File "/Users/jshodd/opt/tools/cloudmapper/commands/report.py", line 322, in report
count = findings_severity_by_account[finding.account_name][ …
```
> Filtering findings for generating reports with multiple accounts

- commands/sg_ips.py
The refactor in 0da236696534f22de68314282c467e519f271851 broke the sg_ips command, this re-imports the function that was moved.
> Fix the sg_ips command

- commands/prepare.py
VpcEndpoint has _parent set to None when the endpoint is not in the vpc filter list.  Skip these objects.
Fixes #625
> Check for node._parent before iterating

- commands/iam_report.py
Allow outputting the IAM report as a json file.
Resolves https://github.com/duo-labs/cloudmapper/issues/637
> Add OutputFormat to IAM report

- commands/iam_report.py
Started investigating the IAM report, and saw inline policies were not shown correctly. Apparently - they are added to the wrong list, the `managed_policies` list.
This fixes that, and they are now shown nicely
> Show inline policies correctly in iam_report

- commands/prepare.py
The up side: it makes the data.json extremely lighter and the webserver cloud map UI faster.
The down side: no details on the nodes.
> add prepare no-node-data flag 

- commands/weboftrust.py
I ran into an account that has OpenID connectors. Until I understand more, I'd rather have it not fail...
> Do not fail on openID connector

- commands/iam_report.py
(cherry picked from commit 2b584515364e7671583ee49965cdf8bc818705cd)
We started using paths for IAM resources, and suddenly the IAM report broke...
> IAM report - when calculating group ARN, take path into account

- commands/iam_report.py
- shared/audit.py
- shared/iam_audit.py
This fixes issue #672 by suppressing the Netflix PolicyUniverse logger where it exists in the project.  Sets `CRITICAL` instead of `WARNING` which is the default.
Tested against my own account data producing the artifacts.
> add logger to set policyuniverse CRITICAL only fixes #672

- commands/collect.py
- commands/prepare.py
Hey!
We started (ab)using ECS tasks, and we reached the ECS describe-stack rate limits. To resolve, I used chunking (there's a limit of 100 tasks per API call)
> Describe ECS tasks in chunks

- requirements.txt
The included dependencies were missing in the new conversion to installation being managed through `pip` and `requirements.txt` file. 
Tested new install in clean `virtualenv` without these packages installed on the host.
> :heavy_plus_sign: Add missing dependencies for drawing stats PNG

- collect_commands.yaml
This fixes #729 by calling EKS `list-clusters` first
> Call EKS list-clusters before describing

- audit_config.yaml
The `AMI_PUBLIC` audit finding was tagged as RDS and should be under EC2.
Thanks
> Edit AMI_PUBLIC group tag

- collect_commands.yaml
* Working from HEAD of main (9e91a9a) of cloudmapper.
* aws-cli/2.0.50 Python/3.8.5 Darwin/19.6.0 source/x86_64
My collect step failed with:
```
...
Summary: 275 APIs called. 1 errors
Failures:
eks.describe_cluster({'cluster': 'example-foo'}): Parameter validation failed:
Missing required parameter in input: "name"
```
which led me to: https://github.com/duo-labs/cloudmapper/issues/729
But the AWS CLI/SDK shows that `describe-cluster` takes `--name` not `--cluster`, so this PR changes the parameter we are passing. And allows `collect` to complete successfully.
> `aws eks describe-cluster` takes --name

- README.md
- commands/configure.py
- shared/organization.py
- utils/strings.py
c.f. #757. Tested on my AWS Organization (test account). 
Sample run when no `config.json` exists:
```
$ python cloudmapper.py configure discover-organization-accounts
Config file does not exist, creating one
INFO:botocore.credentials:Found credentials in environment variables.
$ cat config.json
{
"accounts": [
{
"id": "0xx9",
"name": "master"
},
{
"id": "7xx4",
"name": "dev"
},
{
"id": "4xx1",
"name": "prod"
},
{
"id": "6xx0",
"name": "logging"
},
{
"id": "4xx7",
"name": "security"
}
],
"cidrs": {}
}
```
Example run when `config.json` exists, but with none of the accounts of the organization:
```
$ cat config.json
{
"accounts": [
{
"id": "111",
"name": "idontexist"
}
],
"cidrs": {}
}
$ cloudmapper.py configure discover-organization-accounts
$ cat config.json
{
"accounts": [
{
"id": …
```
> Automatic discovery of AWS Organization member accounts to config.json (closes #757)

- commands/prepare.py
Fixes the Index out of range error in case a collected task is in the failure state for some reason or another.
> Support missing tasks OR multiple tasks per task ARN. Fixes #785

- auditor/package-lock.json
- auditor/package.json
- requirements.txt
General package version bumps.
most importantly:
- policyuniverse is now set to 1.3.2.20201103
- cdk is now set to 1.71.0
> bump policyuniverse and npm packages

- auditor/lib/cloudmapperauditor-stack.js
- auditor/s3_bucket_files/cdk_app.yaml
- auditor/s3_bucket_files/run_cloudmapper.sh
- commands/report.py
- shared/audit.py
- shared/iam_audit.py
This PR aims to enhance the capabilities of the reporting command.
- Sets a new `MINIMUM_REPORT_SEVERITY` that complements the slack `MINIMUM_ALERT_SEVERITY` variable. This variable is defined in `cdk_app.yaml` and defaults to INFO. This is useful for accounts with a large number of INFO-level findings. (ex: `IAM_LINTER`)
- Enables detailed error reporting in Slack. Currently, non-blocking API errors will appear in collect logs and in Cloudwatch. This change allows per-account error counts to be presented. If no errors are detected, previous output message behavior is maintained.
- Suppresses the 1000's of cloudwatch log lines that come from the upload/sync actions from ECS to S3.
- Fixes the `counts-of-findings-by-account` graph in `report.html`
- Clarifies (but does not alter) the …
> Cleaner reporting

- commands/collect.py
On our environment we have SCPs in place that deny access to some services and regions. Since these fail to return data `cloudmapper` encounters an error when reading this data back. This PR fixes that, by only reading the data if the files exist.
> Fixed collect when some services return AccessDenied

- audit_config.yaml
- collect_commands.yaml
- shared/audit.py
Based on [recommended guidance](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-desync-mitigation-mode.html) from AWS, sets a new `ELBV1_DESYNC_MITIGATION` check.
This change includes:
- A new audit_config
- `describe-load-balancer-attributes` collection task, 
- The check logic in `audit.py`,
The check is very similar to the ELBv2 check, but targets a different resource in a different way. 
I don't believe they should be merged, but happy to do so, if needed.
> Desync mitigation check on ELBv1

- commands/weboftrust.py
- shared/audit.py
- shared/common.py
- web/style.json
With cross-account STS-based authentication backed by SAML, this WoT failed to execute as the the two Arn's would never match. (The principal and the provider are not in the same account, by design.)
Here, we replicate the same behavior as before, but also add a fallback model of ensuring we actually trust the origin and target accounts. This allows WoT to graph the unidirectional trust for further inspection.
Additionally, `web/style.json` now includes labels to better understand what the colors mean at a glance. While this data is also available [here](https://summitroute.com/blog/2018/06/13/cloudmapper_wot), it's easier to share the WoT graph with all data present.
Lastly, ensured that any elasticsearch instance without an attached AccessPolicy be marked as `ES_PUBLIC` due to …
> Web of trust STS

- README.md
The existing instructions say you can view the report by running the container with the included instructions.  The instructions do not actually run or expose the webserver.
> Added port mapping and webserver command to Docker instructions

- vendor_accounts.yaml
Adds 3 new vendors to the `vendor_accounts.yaml` list.
- Cisco Umbrella
- Cloudflare
- AWS S3 Log Delivery Service
Note: AWS no longer recommends using the S3 Log Delivery Service with this AWS account and instead recommends you to use ""s3.amazonaws.com"" in principal.
> New vendors

- README.md
When running `pip install`, it error-ed out because I didn't have FreeType installed. This was the specific message:
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/Users/brandonhigh/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/numpy/core/include -I/Users/brandonhigh/.asdf/installs/python/3.9.0/include/python3.9 -c src/checkdep_freetype2.c -o build/temp.macosx-10.15-x86_64-3.9/src/checkdep_freetype2.o …
```
> Add freetype to brew install pre-reqs

- requirements.txt
As commented in https://github.com/duo-labs/cloudmapper/issues/803 the solution from @BenDenney (https://github.com/BenDenney) was to increase `matplotlib` to `3.3.3`
> Fix issue 803

- shared/public.py
Fixing issue #373 
Adding the SG id into the dictionary as a key-value so it can be filtered as described in the issue.
> Fix issue 373

- shared/find_unused.py
The function `find_unused_elastic_load_balancers` only checks for classic ELBs. I added some lines to check for Application, Network and Gateway ELBs. This check is based on the number of instances in all target groups of a ELB
> Find unused ELBv2

- auditor/package-lock.json
- auditor/package.json
#904: Upgraded CDK version to 1.132.0 to avoid install error with node10x deprecation.
> bug: #904 cdk version upgrade for node10x deprecation

- vendor_accounts.yaml
I've had problems in the past with "unknown" and "unremovable" ACM certificates living in my account.  It turns out that creating an API Gateway automatically creates a cert using one of these accounts.  It took me several days to figure this out, but now it appears as if there is an official AWS document showing this information.  :+1: 
Additional info: https://forums.aws.amazon.com/thread.jspa?threadID=315031&tstart=0
> Add API Gateway account ids
